### PR TITLE
#67: Remove web and wiro modules (closes #67)

### LINKED ISSUE #32: CI does not auto-release web
## description

The CI drone releases a `backend` version after every PR is merged, but it does not do the same for the `web`.

This results in having to release `web` manually and in having the `web` and `backend` versions out of sync. 

## how to reproduce
- {optional: describe steps to reproduce bug}

## specs
The CI shall:
* Create a new release commit and tag
* Release both the `web` and the `backend` together

## misc
{optional: other useful info}

### LINKED ISSUE #67: Remove web and wiro modules
## requirements
{describe the new feature}

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
{optional: other useful info}

### LINKED ISSUE #73: Migrate CI to Concourse
We're deprecating Drone.

### PR DESCRIPTION
**Pull request by gabro**
Closes #67
Closes #32 
Closes #73 

### tests performed
CI passes

### CODE REVIEW

File: project/CIRelease.scala [hunk 1]
```diff
@@ -0,0 +1,84 @@
+package com.geirsson
```
Comment (gabro) [inline project/CIRelease.scala]: this file is copy-pasted from https://github.com/olafurpg/sbt-ci-release, and adapted to make it work with Concourse (the original one only works with Travis)

I may publish it as a plugin at some point

File: ci/test.sh [hunk 2]
```diff
@@ -0,0 +1,31 @@
+#! /bin/sh
+
+set -e
+
+source /docker-lib.sh
+echo "Starting docker..."
+start_docker
+echo "Docker started!"
```
Comment (bytecodeguru) [inline ci/test.sh]: leftovers or good practice?

Comment (gabro) [reply ci/test.sh]: good practice, I think :D
